### ISSUE TITLE
Ошибка при получении деталей операции 

### ISSUE THREAD

**Issue by nedden** [RuntimeLLC/moneta-api#47]
Привет! 

Код из примера работает как ожидается, но следующий код вызывает ошибку.
Параметр id беру из существующей операции (продакшен) - целое число.
Что я делаю не так?

```ruby
def get_operation(id)
  service = Moneta::Api::Service.new('user', 'password')
  service.get_operation_details_by_id(id)
end
```

```
Moneta::Api::HTTPException: <html>    <head>        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">        <title>Страница не найдена / Page not found</title>    </head>    <body>        <h1>Страница не найдена / Page not found</h1>    </body></html>
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/moneta-api-1.12.7/lib/moneta/api/service_methods.rb:220:in `rescue in call'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/moneta-api-1.12.7/lib/moneta/api/service_methods.rb:199:in `call'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/moneta-api-1.12.7/lib/moneta/api/service_methods.rb:91:in `get_operation_details_by_id'
	from /vagrant/app/models/backend/payment_transactions/qiwi_withdrawal.rb:30:in `check_operation'
	from (irb):8
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by llxff** [comment]
Привет, спасибо за репорт. 

Пока на первый взгляд что-то не то с генерацией soap запроса для этого метода. Нужно разбираться :)

**Comment by llxff** [comment]
@nedden пока самый простой вариант - явно указать namespace:

```
def get_operation(id)
  service = Moneta::Api::Service.new('user', 'password', namespace: 'http://www.moneta.ru/schemas/messages.xsd')
  service.get_operation_details_by_id(id)
end

```
